apiVersion: batch/v1
kind: Job
metadata:
  name: index-builder-job
  namespace: default
  labels:
    app.kubernetes.io/name: ai-agents
    app.kubernetes.io/component: index-builder
  annotations:
    description: "A one-off job to build the vector store index from scratch."
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: index-builder
    spec:
      restartPolicy: Never
      initContainers:
        - name: fix-permissions
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              mkdir -p /app/vector_store
              chown -R 1000:1000 /app/vector_store
              chmod -R 755 /app/vector_store
          volumeMounts:
            - name: vector-store
              mountPath: /app/vector_store
          securityContext:
            runAsUser: 0  # Run as root to fix permissions
      containers:
        - name: index-builder
          image: ai-agents-backend:latest
          imagePullPolicy: IfNotPresent

          command: ["python", "scripts/build_index.py"]

          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: openai-secret

          env:
            - name: PYTHONPATH
              value: "/app"
            - name: VECTOR_STORE_PATH
              value: "/app/vector_store"

          volumeMounts:
            - name: vector-store
              mountPath: /app/vector_store # This MUST match VECTOR_STORE_PATH above.
            - name: tmp-volume
              mountPath: /tmp

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

      volumes:
        - name: vector-store
          persistentVolumeClaim:
            claimName: backend-pvc
        - name: tmp-volume
          emptyDir: {}
