repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.13.3 # pin the latest stable Ruff
    hooks:
      - id: ruff-check
        args: ["backend/"]
      - id: ruff-format
        args: ["backend/"]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: bash -c 'cd backend && poetry run mypy app/'
        language: system
        files: ^backend/app/.*\.py$
        pass_filenames: false
