services:
  backend:
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./backend/app:/app/app
      - index-data:/app/vector_store
    command: /app/.venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
