apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: default
  labels:
    app: redis
    component: cache
data:
  redis.conf: |
    # Redis configuration for production use
    bind 0.0.0.0
    port 6379
    timeout 300
    tcp-keepalive 60

    # Memory management
    maxmemory 512mb
    maxmemory-policy allkeys-lru

    # Persistence
    save 900 1
    save 300 10
    save 60 10000
    appendonly yes
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb

    # Security
    requirepass ${REDIS_PASSWORD}

    # Logging
    loglevel notice
    logfile ""

    # Client management
    maxclients 10000

    # Slow log
    slowlog-log-slower-than 10000
    slowlog-max-len 128

    # Latency monitoring
    latency-monitor-threshold 100
