name: CI Pipeline

on:
  pull_request:
    branches: [main]

jobs:
  backend-quality-checks:
    name: Backend Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect backend changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'backend/**'
              - '.github/workflows/ci.yml'

      - name: Set up Python 3.12
        if: steps.changes.outputs.backend == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        if: steps.changes.outputs.backend == 'true'
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry dependencies
        if: steps.changes.outputs.backend == 'true'
        uses: actions/cache@v4
        with:
          path: backend/.venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        if: steps.changes.outputs.backend == 'true'
        working-directory: ./backend
        run: poetry install --with dev --no-interaction

      - name: Run Ruff and Mypy
        if: steps.changes.outputs.backend == 'true'
        working-directory: ./backend
        run: |
          poetry run ruff check . --output-format=github
          poetry run ruff format --check .
          poetry run mypy app/ --ignore-missing-imports

  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect backend changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'backend/**'
              - '.github/workflows/ci.yml'

      - name: Set up Python 3.12
        if: steps.changes.outputs.backend == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        if: steps.changes.outputs.backend == 'true'
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry dependencies
        if: steps.changes.outputs.backend == 'true'
        uses: actions/cache@v4
        with:
          path: backend/.venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        if: steps.changes.outputs.backend == 'true'
        working-directory: ./backend
        run: poetry install --with dev --no-interaction

      - name: Set up test environment variables
        if: steps.changes.outputs.backend == 'true'
        run: |
          echo "OPENAI_API_KEY=dummy_key_for_testing" >> $GITHUB_ENV
          echo "REDIS_HOST=localhost" >> $GITHUB_ENV
          echo "REDIS_PORT=6379" >> $GITHUB_ENV
          echo "ENVIRONMENT=test" >> $GITHUB_ENV

      - name: Run Tests with Coverage
        if: steps.changes.outputs.backend == 'true'
        working-directory: ./backend
        run: poetry run pytest --cov=app --cov-fail-under=80
